workflows:
  android-build:
    name: Android Build
    environment:
      node: latest
    scripts:
      - npm install
      - npm install @capacitor/cli
      - npx cap init tracking com.tracking.app --web-dir=www || true
      - npx cap add android || true
      - npx cap sync
      - cd android
      - ls
      - chmod +x gradlew || true
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk
