workflows:
  android-build:
    name: Android Build
    environment:
      node: latest
    scripts:
      - npm install
      - npm install @capacitor/cli
      - npx cap add android
      - npx cap sync
      - cd android
      - ./gradlew assembleDebug
    artifacts:
      - android/app/build/outputs/**/*.apk